### ISSUE TITLE
augment the training images with simple flipping

### ISSUE THREAD

**Issue by qq274983722** [JiYuanFeng/MCTrans#12]
Dear Author
I didn't see the use of simple flipping to enhance the training image in your code

**Comment by JiYuanFeng** [comment]
Hi, please check&nbsp; "Random Mirror" in https://github.com/JiYuanFeng/MCTrans/blob/master/configs/_base_/datasets/pannuke.py




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月14日(星期二) 上午9:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [JiYuanFeng/MCTrans] augment the training images with simple flipping (Issue #12)





 
Dear Author
 I didn't see the use of simple flipping to enhance the training image in your code
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by qq274983722** [comment]
Dear Author
I saw it in the code. Thank you very much for your reply
